import { useEffect, useState } from 'react';
import './App.css';
import axios from 'axios';
import Navbar from './components/Navbar';

const API_URL = 'https://api.unsplash.com/search/photos';

function App() {
  const [region, setRegion] = useState("");
  const [budget, setBudget] = useState("");
  const [dietType, setDietType] = useState("veg"); // default to veg
  const [allergies, setAllergies] = useState("");
  const [answer, setAnswer] = useState("");
  const [imageUrls, setImageUrls] = useState({});

  // Function to generate a diet plan
  async function generateAnswer() {
    setAnswer('Loading...');

    // Construct the question
    let question = `Suggest a diet for a day under ${budget} rupees, `;
    question += `${dietType} diet`;
    if (allergies) question += `, avoiding allergies: ${allergies}`;

    try {
      // Google Generative Language API Request
      const response = await axios.post(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent",
        { contents: [{ parts: [{ text: question }] }] },
        { params: { key: 'AIzaSyDIjHB4cD7WAKZ1-STYom4czbx97IVahEI' } }
      );

      const generatedText = response.data.candidates[0].content.parts[0].text;
      setAnswer(generatedText);

      // Extract food items and fetch images
      const foodItems = extractFoodItems(generatedText);
      foodItems.forEach(food => fetchPhotos(food));

    } catch (error) {
      console.error('Error generating answer:', error);
      setAnswer('Failed to generate a response. Please try again.');
    }
  }

  // Function to fetch photos from Unsplash for a given food item
  async function fetchPhotos(foodItem) {
    try {
      const result = await axios.get(API_URL, {
        params: {
          client_id: 'bVboo6HRExYUIKhHCODEE2pIX8_8ULFX5CSxBFaOKVI', // Your Unsplash API key
          query: foodItem,  // Use the food item to search
        },
      });

      const imageUrl = result.data.results[0]?.urls?.thumb || ''; // Get the first image result
      setImageUrls(prev => ({ ...prev, [foodItem]: imageUrl }));  // Save the image URL in state

    } catch (error) {
      console.error(`Error fetching photos for ${foodItem}:`, error);
    }
  }

  // Function to extract food items from generated text
  const extractFoodItems = (text) => {
    const cleanedText = text.replace(/\*\*/g, ''); // Remove '**' characters
    const sections = cleanedText.split(/(?=Breakfast|Lunch|Dinner)/); // Split on meal titles

    let foodItems = [];
    sections.slice(1).forEach(section => {
      const items = section
        .slice(section.indexOf('\n') + 1)
        .split('*')
        .map(item => item.trim())
        .filter(Boolean);

      // Collect only the first 3 items per meal
      foodItems = [...foodItems, ...items.slice(0, 3)];
    });

    return foodItems;
  };

  // Format the answer generated by AI and display images
  const formatAnswer = (text) => {
    const cleanedText = text.replace(/\*\*/g, ''); // Remove '**' characters
    const sections = cleanedText.split(/(?=Breakfast|Lunch|Dinner)/); // Split on meal titles

    return sections.slice(1).map((section, index) => {
      const title = section.split('\n')[0]; // Meal title
      const items = section
        .slice(section.indexOf('\n') + 1)
        .split('*')
        .map(item => item.trim())
        .filter(Boolean);

      return (
        <div key={index} className="meal-box">
          <h3>{title}</h3>
          <div className="meal-items">
            {items.slice(0, 3).map((item, i) => (
              <div key={i} className="card">
                <p>{item}</p>
                {/* Display image below the item if available */}
                {imageUrls[item] && <img src={imageUrls[item]} alt={item} />}
              </div>
            ))}
          </div>
        </div>
      );
    });
  };

  return (
    <div className='page'>
      <Navbar/>

      <div className="input-box-group">
        <div className="input-row">
          <label className="label">Region:</label>
          <input type="text" value={region} onChange={(e) => setRegion(e.target.value)} />
        </div>
        <div className="input-row">
          <label className="label">Budget:</label>
          <input type="text" value={budget} onChange={(e) => setBudget(e.target.value)} />
        </div>
        <div className="input-row">
          <label className="label">Diet Type:</label>
          <select value={dietType} onChange={(e) => setDietType(e.target.value)}>
            <option value="veg">Vegetarian</option>
            <option value="non-veg">Non-Vegetarian</option>
            <option value="vegan">Vegan</option>
          </select>
        </div>
        <div className="input-row">
          <label className="label">Allergies (optional):</label>
          <input type="text" value={allergies} onChange={(e) => setAllergies(e.target.value)} />
        </div>
        <button className="button" onClick={generateAnswer}>Generate Diet Plan</button>
      </div>

      <div className="answer">
        {answer ? formatAnswer(answer) : null}
      </div>
    </div>
  );
}

export default App;
